CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -Iinclude -g

SRC_DIR = src
TEST_DIR = test
LIB_DIR = lib

SOURCES = $(SRC_DIR)/sat_solver.c
TEST_SOURCE = $(TEST_DIR)/test.c

LIBRARY = $(LIB_DIR)/libsat_solver.a
TEST_EXEC = $(TEST_DIR)/run

all: $(LIBRARY) $(TEST_EXEC)

$(LIBRARY): $(SOURCES)
	@mkdir -p $(LIB_DIR)
	$(CC) $(CFLAGS) -c $(SOURCES) -o $(SRC_DIR)/sat_solver.o
	ar rcs $(LIBRARY) $(SRC_DIR)/sat_solver.o

$(TEST_EXEC): $(TEST_SOURCE) $(LIBRARY)
	@mkdir -p $(TEST_DIR)
	$(CC) $(CFLAGS) $(TEST_SOURCE) -L$(LIB_DIR) -lsat_solver -o $(TEST_EXEC)

test: $(TEST_EXEC)
	./$(TEST_EXEC)

clean:
	rm -rf $(LIB_DIR) $(TEST_EXEC) $(SRC_DIR)/*.o

.PHONY: all test clean